algo = input('digite algo: ')
print('o tipo primitivo desse valor é {}'.format(type(algo)))
print('é alphanumerico??', algo.isalnum())
print('é alfabetico?', algo.isalpha())
print('esta em minusculo?', algo.islower())
print('é um numero?', algo.isnumeric())
print('esta em maiusculo?', algo.isupper())
print('so tem espaço?', algo.isspace())
print('é capitalizado?', algo.istitle())
